### ISSUE TITLE
Custom mounting point

### ISSUE THREAD

**Issue by Fxlr8** [haradakunihiko/react-confirm#12]
How about implementing the ability to change confirmation mounting point. Now it is mounted directly to the body. This causes problems when used with libraries that require a parent wrapper for app's root component like `redux` or `react-intl`. The confirmation window is mounted outside of this structure and cannot access the redux store.

**Comment by haradakunihiko** [comment]
Sorry, didn't have a time to check this issue.
I realize we can not access redux store inside the confirmation component. Yes, it needs to be in the tree. But the important thing is, it must be placed inside the component tree, not DOM tree. So specifying mounting point would not solve the problem.
So in my project, I wrap `createConfirmation` and pass redux's `store` directory as props and create new redux tree as workaround, something like bellow.

```js
import { Provider } from 'react-redux';
import createConfirmation from 'react-confirm'

// HOC
const Wrapper = (Component, store) => (props) => (<Provider store={store}><Component {...props} /></Provider>)

const confirmation = {
  init() {
    return (store) => {
      this.store = store;
    };
  },
  wrappedCreateConfirmation() {
    return (Component) => createConfirmation(Wrapper(Component, store));
  },
};

export const initialize = confirmation.init();
export default confirmation.wrappedCreateConfirmation();

```

And call `initialize` when  redux's store is initialized, use the default export above instead for creating confirmation function.
But one thing, creating multiple redux mounting point (Provider) cause complexity. You can not get some of the benefits of redux. Definitely, this is not the best practice and if you need redux's store inside dialog, it has to be implemented in a normal way without this library. (But I crossed the line and used it... )
The code above is kind of pseudocode, it won't work but the idea is something like that.

I don't know well about `react-intl`, sorry.

But apart from that, adding mounting point may be necessary for some reason. If you create PR, it's very welcomed.

**Comment by haradakunihiko** [comment]
The problem is that the same `context` for the redux's component tree is needed. But I do not have a good idea to share that. That's why I created another React tree with Provider.

If there is any good idea, I'm very looking forward to changing the library. Really!

**Comment by Fxlr8** [comment]
Libraries like `redux`, `react-router`, `react-intl` require a global "provider" component in your project root, so rendering anything outside of them causes troubles like the one you faced. I don't think it is a good idea to render redux provider every time you want to show confirmation window. It would be nice to be able to render a component somewhere in your app and render all confirmations inside it. Something like react-gateway

**Comment by haradakunihiko** [comment]
Yep, you're right. it is not a good idea at all. Just currently, there is no other option if you want to use some library which needs react's context.
The motivation for this `react-confirm` library is that I do not want to do any extra work for just showing yes/no dialog especially when I need many dialogs. Call a function and show the dialog, that's it.

I think react-gateway is not good enough, but maybe it could be some hint to solve this problem.

**Comment by JsanchezSeyte** [comment]
In my case i solved for react-intl the next way, in case some one need it:
```
    confirmEmptyCart() {
        confirm**(this.props.intl.formatMessage({ id: 'EMPTY_CART_CONFIRM' }))**.then(
            confirm => {
                this.props.emptyCart()
            },
            cancel => {}
        )
    }
```
