### ISSUE TITLE
Close on navigation

### ISSUE THREAD

**Issue by TheRusskiy** [haradakunihiko/react-confirm#16]
Right now if browser changes location (in SPA) the dialog stays open, an option for the dialog to be dismissed if this happens would be nice.

**Comment by LiranBri** [comment]
+1

**Comment by GramozKrasniqi** [comment]
It is not only nice but a must. There must be a way to programmatically close the dialog.
There is nothing in the documentation and i have looked into the code but couldn't find any way.

**Comment by TheRusskiy** [comment]
I've done something like:
```
const history = createBrowserHistory()
window.reactRouterHistory = history
...
class ConfirmationDialog extends React.Component {
...
  componentDidMount() {
    this.unlisten = window.reactRouterHistory.listen(() => {
      this.props.cancel()
    })
  }

  componentWillUnmount() {
    this.unlisten()
  }
...
}
```

**Comment by haradakunihiko** [comment]
Thanks for the suggestion.

As TheRusskiy noted, proceed, cancel, dismiss function are available anytime you need.

If there is better solution as a library, PR is welcomed!
