### ISSUE TITLE
Suggestion: Provide Screenshot Example/Live Demo

### ISSUE THREAD

**Issue by MikeShi42** [haradakunihiko/react-confirm#23]
Hello, just wanted to point out that there's a high hurdle to trying out this lib. Would be at least good to have a screenshot in the readme so I know what kind of confirmation I should be expecting. Even better would be a live demo. There's plenty of places that can host a live demo for you such as https://codesandbox.io/ which would go a long way to convince me that this lib is a good fit for my use case.

**Comment by haradakunihiko** [comment]
OK! I will update Readme later with SS.
