### ISSUE TITLE
Not open dialog in popup

### ISSUE THREAD

**Issue by ankitpatelinitio** [haradakunihiko/react-confirm#24]
Hello
  I am implemented this in my code but not open confirm dialog in a popup. I attached screenshot of this issue. So please give me a solution for this issue.

![Project Management](https://user-images.githubusercontent.com/48117127/57766967-f3d79d00-7725-11e9-9aac-b6eb8c74a81a.png)

Thanks

**Comment by ahmedafe1** [comment]
me too

**Comment by haradakunihiko** [comment]
Please give me more specific information.
