### ISSUE TITLE
React >= 0.15.0

### ISSUE THREAD

**Issue by shir** [haradakunihiko/react-confirm#3]
Looks like only React 0.14 is supported now. Any chances to update for React 0.15? I guess it should not be hard.

**Comment by haradakunihiko** [comment]
Yes, there is no problem with 15, so I will change that. Thanks.

**Comment by haradakunihiko** [comment]
Updated. Now you can use with react 5.

**Comment by shir** [comment]
@haradakunihiko thank you!
