### ISSUE TITLE
npm install fail cause of a redundant comma in react-bootstrap example

### ISSUE THREAD

**Issue by playtocrazy** [haradakunihiko/react-confirm#4]
npm install fail cause of a redundant comma in [package.json of react-bootstrap example at Line:26](https://github.com/haradakunihiko/react-confirm/blob/master/example/react-bootstrap/package.json#L26)

> npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\richard.lin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.10.8
npm ERR! file D:\Github\react-confirm\example\react-bootstrap\package.json
npm ERR! code EJSONPARSE

>npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 27:1
npm ERR! }
npm ERR! ^
npm ERR! File: D:\Github\react-confirm\example\react-bootstrap\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

>npm ERR! Please include the following file with any support request:
npm ERR!     D:\Github\react-confirm\example\react-bootstrap\npm-debug.log

**Comment by haradakunihiko** [comment]
Thanks!!
I just pushed master branch. Please check out again.

**Comment by playtocrazy** [comment]
ok, thanks.
