### ISSUE TITLE
Is there any branch i can use with typescript?

### ISSUE THREAD

**Issue by uhahula** [haradakunihiko/react-confirm#47]
Is there any branch i can use with typescript?

**Comment by haradakunihiko** [comment]
There is no official type definition in this repository, and [@types](https://www.npmjs.com/package/@types/react-confirm) seems to have a wrong interface...

Sorry, but I do not have time to prepare that right now. 
PR is welcomed!

**Comment by jbovone** [comment]
The types are ok, remember that they need to support older version. The semver here is wrong. You issue a patch then modified all the signatures.

The DTD won't allow a new version unless you issue a mayor release.

**Comment by haradakunihiko** [comment]
For example, the arguments of `proceed` was never string since the first release. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-confirm/index.d.ts#L16

But, I think you are right. I should carefully set the version for some releases.
In that case, I already released 0.2 a few months ago. Does that help?

**Comment by jbovone** [comment]
@haradakunihiko well that might happen to be a mistake. But the thing is that it's difficult to anyone but you to verify this... 

Other will need to manually check every minor and bug fix releases before realize that the type it doesn't match to any. 
 
Yo need to issue a MAYOR if you change signatures. Is the only way that you can preserve integrity. 

For instance, if you issue this change as a  MINOR:
`const createConfirmation = (Component) => {`
`const createConfirmation = (Component, unmountDelay = 1000, mountingNode) => {`

Only one will be supported. As a MAYOR the two versions can be typed.

**Comment by haradakunihiko** [comment]
@jbovone Actually, I'm not very used to type def things, so your comment is really helpful.
What does it mean by `MAYOR` in `Yo need to issue a MAYOR`?
What should I do as this library maintainer?

**Comment by haradakunihiko** [comment]
@uhahula
Try https://github.com/haradakunihiko/react-confirm/tree/typescript#typescript !

**Comment by baselbj** [comment]
> Ref

for yarn use yarn add git+ssh://git@github.com:haradakunihiko/react-confirm.git#typescript

**Comment by haradakunihiko** [comment]
released!
