### ISSUE TITLE
ChakraUI forgetting stylization

### ISSUE THREAD

**Issue by mariosantosdev** [haradakunihiko/react-confirm#61]
I'm using ChakraUI to styles my application. I follow the example of [react-bootrstap](https://codesandbox.io/s/react-confirm-with-react-bootstrap-kjju1) but when the dialog is open the stylization of ChakraUI forgot. I think it's caused because the Portal.

**Comment by haradakunihiko** [comment]
@mariosantosdev 
I'm not very familiar with Chakra UI, but it seems to use context based on what I see on https://chakra-ui.com/. 
Currently, we can't use context with react-confirm. However, it is planned to be improved in https://github.com/haradakunihiko/react-confirm/pull/60, but it may take another one or two weeks until the release. 

If you want to try it before then, try `npm install git@github.com:haradakunihiko/react-confirm.git#feature/implement-to-use-context`. See https://github.com/haradakunihiko/react-confirm/blob/4a55a0b0bc120639931312ff030304bc93d8f64f/README.md#using-with-context for detail. 

Putting `MountPoint` under `ChakarProvider` tree may fix your issue.

**Comment by mariosantosdev** [comment]
Thanks @haradakunihiko. I guess it's better to wait until the release.
