### ISSUE TITLE
How to make confirm blocking?

### ISSUE THREAD

**Issue by CoralSilver** [haradakunihiko/react-confirm#7]
Is there a way I can make calling confirm blocking like with window.confirm?

**Comment by liang3404814** [comment]
Instead of making it really blocking, I would also consider using something like a <Dialog> from material-ui or write your full screen modal so users have to interact with the confirm first.

**Comment by haradakunihiko** [comment]
I do not quite understand what you want to achieve. Like @liang3404814 said, you can block the screen with some dialog component and can trigger any function after the dialog disappeared. If you literally want to stop javascript execution, I do not have good solution. (But why?)

**Comment by CoralSilver** [comment]
Thanks. I had to ask plugin author for react-bootstrap-table to make some changes to implementation so I could add callback to confirm. Sorry not related to this repo.
